// This file is auto-generated by the GitHub Actions workflow.
// DO NOT edit manually — changes will be overwritten on next workflow run.
// It exposes GH_PAT and GH_REPO as window globals so the browser (Option B)
// can push positions.json without storing a PAT in localStorage.
window.__GH_PAT  = '';
window.__GH_REPO = '';
