// Auto-generated by GitHub Actions — DO NOT edit manually.
// Exposes secrets as window globals so the browser can send Telegram alerts
// and push positions.json without storing credentials in localStorage.
window.__GH_PAT   = '';
window.__GH_REPO  = '';
window.__TG_TOKEN = '';
window.__TG_CHAT  = '';
