// Auto-generated by GitHub Actions — DO NOT edit manually.
// Credentials are written at runtime and reset here before commit.
// The browser receives live values via GitHub Pages during workflow run.
window.__GH_PAT    = '';
window.__GH_REPO   = '';
window.__TG_TOKEN  = '';
window.__TG_CHAT   = '';
